config/routes.rb
Rails.application.routes.draw do
  resources :labels, only: [:show]

  resources :topics do
    resources :posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up_vote' => 'votes#up_vote', as: :up_vote
    post '/down_vote' => 'votes#down_vote', as: :down_vote
  end
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  get 'about' => 'welcome#about'

  root 'welcome#index'

    namespace :api do
      namespace :v1 do
        resources :users, only: [:index, :show, :create, :update]
        resources :topics, except: [:edit, :new]
      end
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<h1>About Bloccit</h1>
<p>Created by: Me</p>
<%= link_to "Follow me", "/", class: "social-btn", width:100, height:100 %>

app/views/welcome/contact.html.erb
<p>Hello, Welcome to my page.</p>

app/views/welcome/faq.html.erb
<p>This is my Frequent Asked Questions Page!</p>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron">
  <h1>Bloccit</h1>
    <p>Bloccit is a resource for sharing links with your friend!</p>
         <% if current_user %>
         <%= current_user.name %> - <%= link_to "Sign Out", session_path(current_user), method: :delete %>
       <% else %>
         <%= link_to "Sign In", new_session_path %> or
         <%= link_to "Sign Up", new_user_path %>
       <% end %>
  </div>

<div class="row">
  <div class="col-md-4">
    <h2>Solves world hunger</h2>
    <p>Bloccit will deliver food and water to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Eliminates poverty</h2>
    <p>Bloccit will deliver money and education to those in need, all over the world.</p>
  </div>
  <div class="col-md-4">
    <h2>Makes you better looking</h2>
    <p>Bloccit will make you better looking: it's scientifically proven to make men look like Ryan Gosling and women look like Shakira.</p>
  </div>
</div>